stages:
    - test
    - examples

test_docker:
    stage: test
    image: ubuntu:rolling
    tags: 
            - docker.meteo.physik.lmu.de
    # Since enstools is a dependency, we still need to install all these libraries.
    before_script:
            - apt update
            - export DEBIAN_FRONTEND=noninteractive
            - apt-get install -y libproj-dev proj-data proj-bin
            - apt-get install -y libgeos-dev
            - apt-get install -y libeccodes-dev
            - apt install -yq git python3 python3-pip python3-venv
    script: ./run_tests.sh
